services:
  web:
    build: .
    command: sh -c "uvicorn app.main:app --reload --port=8000 --host=0.0.0.0 >> /app/logs/app.log 2>&1"
    restart: unless-stopped
    env_file:
      - .env
    ports:
      - "${PORT}:8000"
    volumes:
      - .:/app
      - ./logs:/app/logs  # Montamos la carpeta de logs en el host